config = { }


[templates.pywalfox-update]
input_path = "~/.config/noctalia/templates/pywalfox-update.sh"
output_path = "~/.cache/wal/pywalfox-update.sh"
post_hook = "bash ~/.cache/wal/pywalfox-update.sh"
